"""
Export helpers — Word (.docx) and plain text (.txt).
All in-memory, no disk writes.
"""
import io
from datetime import datetime


def generate_txt_bytes(data: dict, product_name: str = "") -> bytes:
    """Plain text export."""
    lines = []
    lines.append("=" * 60)
    lines.append("  AI MARKETING STRATEGY REPORT")
    lines.append(f"  Generated: {datetime.now().strftime('%B %d, %Y')}")
    if product_name:
        lines.append(f"  Product: {product_name}")
    lines.append("=" * 60)
    lines.append("")

    for section, content in data.items():
        if section.startswith("_meta"):
            continue
        lines.append(f"{'─' * 50}")
        lines.append(f"  {section.upper()}")
        lines.append(f"{'─' * 50}")
        clean_lines = [l.strip() for l in content.split("\n") if l.strip()]
        lines.append("\n".join(clean_lines))
        lines.append("")

    lines.append("─" * 60)
    lines.append("Generated by Groq + LLaMA 3.1 | Agentic AI System")
    return "\n".join(lines).encode("utf-8")


def generate_docx_bytes(data: dict, product_name: str = "") -> bytes:
    """Word document export using python-docx."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("python-docx is required for Word export. Run: pip install python-docx")

    doc = Document()

    # Title
    title = doc.add_heading("AI Marketing Strategy Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub.add_run(f"Generated by Groq + LLaMA 3.1  ·  {datetime.now().strftime('%B %d, %Y')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    if product_name:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(f"Product / Idea: {product_name}")
        r.font.bold = True
        r.font.size = Pt(12)
        r.font.color.rgb = RGBColor(0x7C, 0x3A, 0xED)

    doc.add_paragraph()  # spacer

    ACCENT_COLORS = [
        RGBColor(0x7C, 0x3A, 0xED),
        RGBColor(0x25, 0x63, 0xEB),
        RGBColor(0x05, 0x96, 0x69),
        RGBColor(0xD9, 0x77, 0x06),
        RGBColor(0xDB, 0x27, 0x77),
        RGBColor(0xEA, 0x58, 0x0C),
        RGBColor(0x16, 0xA3, 0x4A),
        RGBColor(0x02, 0x84, 0xC7),
        RGBColor(0x93, 0x33, 0xEA),
    ]

    for i, (section, content) in enumerate(data.items()):
        if section.startswith("_meta"):
            continue
        heading = doc.add_heading(section, level=2)
        for run in heading.runs:
            run.font.color.rgb = ACCENT_COLORS[i % len(ACCENT_COLORS)]

        for line in content.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith(("- ", "• ", "* ")):
                p = doc.add_paragraph(line[2:], style="List Bullet")
            else:
                clean = line.replace("**", "").replace("__", "")
                doc.add_paragraph(clean)

    # Footer
    doc.add_paragraph("─" * 40)
    footer = doc.add_paragraph(
        "This report was generated by an Agentic AI system. "
        "Strategies are illustrative and should be validated with real market research."
    )
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
