import io
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm

ACCENTS = [
    "#7c3aed", "#2563eb", "#059669", "#d97706",
    "#db2777", "#ea580c", "#16a34a", "#0284c7", "#9333ea"
]

TEXT_MAIN = colors.HexColor("#1e293b")
TEXT_BODY = colors.HexColor("#374151")
TEXT_SUB  = colors.HexColor("#6b7280")
PURPLE    = colors.HexColor("#7c3aed")


def generate_pdf_bytes(data: dict, product_name: str = "") -> bytes:
    """
    Generate PDF entirely in memory and return raw bytes.
    Safe for concurrent users — no disk writes.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=18*mm, leftMargin=18*mm,
        topMargin=20*mm, bottomMargin=18*mm
    )
    styles = getSampleStyleSheet()

    title_s = ParagraphStyle(
        "MyTitle", parent=styles["Title"],
        fontSize=24, textColor=TEXT_MAIN, spaceAfter=4, leading=30
    )
    subtitle_s = ParagraphStyle(
        "MySub", parent=styles["Normal"],
        fontSize=10, textColor=TEXT_SUB, spaceAfter=2
    )
    product_s = ParagraphStyle(
        "MyProduct", parent=styles["Normal"],
        fontSize=13, textColor=PURPLE,
        fontName="Helvetica-Bold", spaceAfter=16
    )
    body_s = ParagraphStyle(
        "MyBody", parent=styles["Normal"],
        fontSize=10, textColor=TEXT_BODY, leading=18, spaceAfter=5
    )
    bullet_s = ParagraphStyle(
        "MyBullet", parent=body_s,
        leftIndent=14, bulletIndent=4, spaceAfter=4
    )
    footer_s = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontSize=8, textColor=TEXT_SUB, leading=12
    )

    story = []

    # Cover
    story.append(Paragraph("AI Marketing Strategy Report", title_s))
    story.append(Paragraph(
        f"Generated by Groq + LLaMA 3.1 &nbsp;·&nbsp; {datetime.now().strftime('%B %d, %Y')}",
        subtitle_s
    ))
    if product_name:
        story.append(Paragraph(f"Product / Idea: {product_name}", product_s))
    story.append(HRFlowable(width="100%", thickness=2.5, color=PURPLE, spaceAfter=20))

    # Sections
    for i, (section, text) in enumerate(data.items()):
        accent = colors.HexColor(ACCENTS[i % len(ACCENTS)])
        heading_s = ParagraphStyle(
            f"H_{i}", parent=styles["Heading2"],
            fontSize=13, textColor=accent,
            fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=4
        )
        story.append(Paragraph(section, heading_s))
        story.append(HRFlowable(width="100%", thickness=0.6, color=accent, spaceAfter=7))

        for line in text.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith(("- ", "• ", "* ")):
                story.append(Paragraph(f"• {line[2:]}", bullet_s))
            elif line.startswith(("**", "__")):
                clean = line.replace("**", "").replace("__", "")
                story.append(Paragraph(f"<b>{clean}</b>", body_s))
            else:
                story.append(Paragraph(line, body_s))

        story.append(Spacer(1, 6))

    # Footer
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=TEXT_SUB, spaceAfter=8))
    story.append(Paragraph(
        "This report was generated by an Agentic AI system using Groq + LLaMA 3.1. "
        "Strategies are illustrative and should be validated with real market research.",
        footer_s
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


# Keep backward-compat shim (writes to disk) — not used by app.py anymore
def generate_pdf(data: dict, product_name: str = "", filename: str = "marketing_report.pdf") -> str:
    with open(filename, "wb") as f:
        f.write(generate_pdf_bytes(data, product_name))
    return filename
